DATA SEGMENT
    NUM1 DD 1234H
    NUM2 DD 1111H
    RESULT DD ?
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:
        MOV AX,DATA
        MOV DS,AX
        MOV AX,WORD PTR NUM1
        MOV BX,WORD PTR NUM2
        MUL BX
        MOV WORD PTR RESULT,AX
        MOV WORD PTR RESULT+2,DX
CODE ENDS
END START