DATA SEGMENT
    NUM1 DD 88888888H
    NUM2 DD 11111111H
    RESULT DD ?
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:
        MOV AX,DATA
        MOV DS,AX
        MOV AX,WORD PTR NUM1
        MOV BX,WORD PTR NUM2
        ADC AX,BX
        MOV WORD PTR RESULT,AX
        MOV BX,WORD PTR NUM1+2
        MOV CX,WORD PTR NUM2+2
        ADC BX,CX
        MOV WORD PTR RESULT+2,BX
CODE ENDS
END START