ORG 00H 
MOV R0, #42H ;NUMBER WHICH WE NEED TO CONVERT INTO DECIMAL
MOV A, R0 
MOV B, #0AH 
DIV AB 
MOV R1, B 
MOV B, #0AH
DIV AB
MOV R2, A 
MOV A, B 
MOV B, #010H 
MUL AB 
ADD A, R1 
MOV R1, A ;HIGHER BYTE OF RESULT IN R2 LOWER IN R1 
END