DATA SEGMENT
    NUM1 DD 1ABC0489H
    NUM2 DD FFFFH
    Q DD ?
    R DD ?
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:
        MOV AX,DATA
        MOV DS,AX
        MOV AX,WORD PTR NUM1
        MOV DX,WORD PTR NUM1+2
        MOV BX,NUM2
        DIV BX
        MOV WORD PTR Q,AX
        MOV WORD PTR R,DX
CODE ENDS
END START